/****************************************************************************************************
                                    389. Find the Difference            
-----------------------------------------------------------------------------------------------------
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
****************************************************************************************************/
#include "problems\problems\Header.h"

namespace std
{

	class Solution {
	public:
	    char findTheDifference(string s, string t) {
	        if (s.size()==0) return t[0];
	        char rst=t[t.size()-1];
	        for(int i=0;i<s.size();i++)
	        {
	            rst^=s[i];
	            rst^=t[i];
	        }
	        return rst;
	    }
	};

}

/****************************************************************************************************
                                             Note
XOR...
****************************************************************************************************/